version: '3'
services:
  nginx:
   container_name: nginxsrv
   image: nginx:latest
   restart: always
   ports:
   - 80:80
   volumes:
   - ./nginx/conf.d:/etc/nginx/conf.d
   networks:
     - appnet

  app:
    container_name: application_container
    restart: always
    build: ./app
    working_dir: /app
    volumes:
      - ./app:/app
      - ~/.m2:/root/.m2
    expose:
      - "8080"
    depends_on:
      - nginx
    networks:
      - appnet
    command: mvn clean spring-boot:run -Dspring-boot.run.profiles=docker

networks:
  appnet: